# Generated by Django 4.1.1 on 2022-10-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSubscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='categories',
            name='names',
            field=models.CharField(choices=[('Email Marketing', 'Email Marketing'), ('Instagram Markerting', 'Instagram Markerting'), ('Sales prospect', 'Sales Prospect'), ('Cusomer retain', 'Cusomer Retain'), ('Sales Process', 'Sales Process'), ('Customers Experience', 'Customers Experience'), ('Sales Qualification', 'Sales Qualification'), ('Remote work', 'Remote Work')], max_length=50),
        ),
    ]
