# Generated by Django 4.1.1 on 2022-10-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_emailsubscribers_alter_categories_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='names',
            field=models.CharField(choices=[('Email Marketing', 'Email Marketing'), ('Performance Management', 'Performance Management'), ('KPI Analytics', 'Kpi Analytics'), (' Human Resource Management', 'Human Resource Management'), ('Payroll_Management', 'Payroll Management'), ('Leave Management', 'Leave Management')], max_length=50),
        ),
    ]
